pipeline {
    environment {
        repository = "hggew/icon"
        DOCKERHUB_CREDENTIALS = credentials('docker_credentials')
        dockerImage = ''
        DISCOVERY_SERVER="${env.DISCOVERY_SERVER}"
    }

    agent any
    
    stages {
        stage('Checkout') {
            steps {
                script {
                    // chat 디렉토리에서 변화가 있을 때만 빌드
                    def changes = sh(script: "git diff --name-only HEAD HEAD~1", returnStdout: true).trim()
                    if (changes.contains("back/chat-service/")) {
                        echo 'Changes in chat directory, proceeding with build.'
                    } else {
                        echo 'No changes in chat directory, skipping build.'
                        currentBuild.result = 'NOT_BUILT'
                        error('No changes in chat directory. Halting pipeline.')
                    }

                    // 코드 체크아웃
                    checkout scm
                }
            }
        }

        // application.yml
        stage('secret.yml delete') {
            steps {
                script{
                    sh 'rm -f /var/jenkins_home/workspace/back-chat/back/chat-service/src/main/resources/application.yml'

                    echo "delete application.yml"

                    sh '''cd /var/jenkins_home/workspace/back-chat/back/chat-service/src/main
                    mkdir -p resource
                    ls -al
                    '''
                }
            }
        }

        stage('secret.yml download') {
        	steps {
            	withCredentials([file(credentialsId: 'back-chat-application', variable: 'applicationFile')]) {
                	script {
                        echo "download application.yml"
                    	sh 'cp -f $applicationFile /var/jenkins_home/workspace/back-chat/back/chat-service/src/main/resources/application.yml'
                    }
        		}
            }
        }



        stage('Build Chat-Server .JAR') {
            steps {
                script {
                    // 변경된 브랜치와 머지 대상 브랜치 출력
                    // 현재 빌드 중인 브랜치명 확인
                    def currentBranch = env.BRANCH_NAME
                    echo "Merge Target Branch : \${CHANGE_TARGET}"
                    echo "Current Branch: \${currentBranch}"

                    echo "chat server 입니다."
                    sh 'pwd'
                    sh 'ls -al'

                    //gradlew 빌드
                    sh 'java --version'
                    sh 'chmod -R u+w+x /var/jenkins_home/workspace/back-chat/back/chat-service/gradlew'

                    sh '''cd /var/jenkins_home/workspace/back-chat/back/chat-service
                    ls -al
                    '''

                    dir('/var/jenkins_home/workspace/back-chat/back/chat-service') {
                        sh './gradlew clean build'
                    }
                }
            }
        }

        stage('Build Chat-Server Image'){
            steps{
                script{
                    dockerImage = docker.build("${repository}:icon-chat_${BUILD_NUMBER}", "--platform linux/amd64 -f back/chat-service/Dockerfile ./back/chat-service")
                }
            }
        }

        stage('DockerHub Login'){
            steps{
                script{
                    sh "echo \${DOCKERHUB_CREDENTIALS_PSW} | docker login -u \${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                }
            }
        }

        stage('Push Chat-Server Image to DockerHub'){
            steps {
                script {
                    sh "docker push \${repository}:icon-chat_\${BUILD_NUMBER}"
                }
            }
        }

        stage('Clean Chat-Server Image'){
            steps{
                script{
                    sh "docker rmi \${repository}:icon-chat_\${BUILD_NUMBER}"
                }
            }
        }

        stage("Garbage Collect TESTSERV") {
            steps {
                sshPublisher(
                    continueOnError: true, failOnError: false,
                    publishers: [
                        sshPublisherDesc(
                            configName: "icon-ssh",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "sudo docker kill \$(docker ps | grep icon-chat | tr ' ' '\t' | cut -f1)"),
                                sshTransfer(execCommand: "sudo docker container prune -f"),
                                sshTransfer(execCommand: "sudo docker image prune -af"),
                                sshTransfer(execCommand: "sudo docker ps -a")
                            ]
                        )
                    ]
                )
            }
        }

        stage("Deploy"){
            steps{
                sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "icon-ssh",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "sudo docker rm -f icon-chat"),
                                sshTransfer(execCommand: "sudo docker pull " + repository +":icon-chat_${BUILD_NUMBER}"),
                                sshTransfer(execCommand: "sudo docker run -d -P --name icon-chat --network host -e DISCOVERY_SERVER=\"${DISCOVERY_SERVER}\" " + repository + ":icon-chat_${BUILD_NUMBER}")
                            ]
                        )
                    ]
                )
            }
        }
    }
}
