pipeline {
    environment {
        repository = "hggew/icon"
        DOCKERHUB_CREDENTIALS = credentials('docker_credentials')
        dockerImage = ''
        DISCOVERY_SERVER="${env.DISCOVERY_SERVER}"
    }

    agent any
    
    stages {
        stage('Checkout') {
            steps {
                script {
                    // 코드 체크아웃
                    checkout scm
                }
            }
        }

        // application.yml
        stage('secret.yml delete') {
            steps {
                script{
                    sh 'rm -f /var/jenkins_home/workspace/back-alarm/back/alarm-service/src/main/resources/application.yml'

                    echo "delete application.yml"

                    sh '''cd /var/jenkins_home/workspace/back-alarm/back/alarm-service/src/main/resources
                    ls -al
                    '''
                }
            }
        }

        stage('secret.yml download') {
        	steps {
            	withCredentials([file(credentialsId: 'back-alarm-application', variable: 'applicationFile')]) {
                	script {
                        echo "download application.yml"
                    	sh 'cp -f $applicationFile /var/jenkins_home/workspace/back-alarm/back/alarm-service/src/main/resources/application.yml'
                    }
        		}
            }
        }



        stage('Build Alarm-Server .JAR') {
            steps {
                script {
                    // 변경된 브랜치와 머지 대상 브랜치 출력
                    // 현재 빌드 중인 브랜치명 확인
                    def currentBranch = env.BRANCH_NAME
                    echo "Merge Target Branch : \${CHANGE_TARGET}"
                    echo "Current Branch: \${currentBranch}"

                    echo "alarm server 입니다."
                    sh 'pwd'
                    sh 'ls -al'

                    //gradlew 빌드
                    sh 'java --version'
                    sh 'chmod -R u+w+x /var/jenkins_home/workspace/back-alarm/back/alarm-service/gradlew'

                    sh '''cd /var/jenkins_home/workspace/back-alarm/back/alarm-service
                    ls -al
                    '''

                    dir('/var/jenkins_home/workspace/back-alarm/back/alarm-service') {
                        sh './gradlew clean build'
                    }
                }
            }
        }

        stage('Build Alarm-Server Image'){
            steps{
                script{
                    dockerImage = docker.build("${repository}:icon-alarm_${BUILD_NUMBER}", "--platform linux/amd64 -f back/alarm-service/Dockerfile ./back/alarm-service")
                }
            }
        }

        stage('DockerHub Login'){
            steps{
                script{
                    sh "echo \${DOCKERHUB_CREDENTIALS_PSW} | docker login -u \${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                }
            }
        }

        stage('Push Alarm-Server Image to DockerHub'){
            steps {
                script {
                    sh "docker push \${repository}:icon-alarm_\${BUILD_NUMBER}"
                }
            }
        }

        stage('Clean Alarm-Server Image'){
            steps{
                script{
                    sh "docker rmi \${repository}:icon-alarm_\${BUILD_NUMBER}"
                }
            }
        }

        stage("Garbage Collect TESTSERV") {
            steps {
                sshPublisher(
                    continueOnError: true, failOnError: false,
                    publishers: [
                        sshPublisherDesc(
                            configName: "icon-ssh",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "sudo docker kill \$(docker ps | grep icon-alarm | tr ' ' '\t' | cut -f1)"),
                                sshTransfer(execCommand: "sudo docker image prune -af"),
                                sshTransfer(execCommand: "sudo docker container prune -f"),
                                sshTransfer(execCommand: "sudo docker ps -a")
                            ]
                        )
                    ]
                )
            }
        }

        stage("Deploy"){
            steps{
                sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "icon-ssh",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "sudo docker rm -f icon-alarm"),
                                sshTransfer(execCommand: "sudo docker pull " + repository +":icon-alarm_${BUILD_NUMBER}"),
                                sshTransfer(execCommand: "sudo docker run -d -p 8082:8082 --name icon-alarm --network icon_bridge -e DISCOVERY_SERVER=\"${DISCOVERY_SERVER}\" " + repository + ":icon-alarm_${BUILD_NUMBER}")
//                                 sshTransfer(execCommand: "sudo docker run -d -p 8888:8888 --name chatting  -e CHATTING_SERVER=\"${CHATTING_SERVER}\" -e DISCOVERY_SERVER=\"${DISCOVERY_SERVER}\"   -e COMMON_SERVER=\"${COMMON_SERVER}\" " + repository + ":chatting_${BUILD_NUMBER}")

                            ]
                        )
                    ]
                )
            }
        }
    }
}
