pipeline {
    environment {
        dockerImage = ''
        ENV_FILE = credentials('env-file')
    }

    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    // 코드 체크아웃
                    checkout scm
                }
            }
        }


        stage('Build Image') {
            steps {
                script {
                    dockerImage = docker.build("frontend", "-f front/Dockerfile ./front") // Dockerfile 경로 수정
                }
            }
        }

        stage("Kill existing frontend container") {
            steps {
                script {
                    def existingContainers = sh(script: "docker ps -aq -f name=frontend", returnStdout: true).trim()
                    if (existingContainers) {
                        sh "docker stop ${existingContainers}"
                        sh "docker rm -f ${existingContainers}"
                    }
                }
            }
        }

        stage("Run frontend container") {
            steps {
                script {
                    sh "docker run -d -p 80:80 --name frontend --env-file ${ENV_FILE} frontend"
                }
            }
        }


    }
}
