pipeline {
    environment {
        repository = "hggew/icon"
        DOCKERHUB_CREDENTIALS = credentials('docker_credentials')
        dockerImage = ''
        DISCOVERY_SERVER="${env.DISCOVERY_SERVER}"
    }

    agent any
    
    stages {
        stage('Checkout') {
            steps {
                script {
                    // analyze 디렉토리에서 변화가 있을 때만 빌드
                    def changes = sh(script: "git diff --name-only HEAD HEAD~1", returnStdout: true).trim()
                    if (changes.contains("back/analyze-service/")) {
                        echo 'Changes in analyze directory, proceeding with build.'
                    } else {
                        echo 'No changes in analyze directory, skipping build.'
                        currentBuild.result = 'NOT_BUILT'
                        error('No changes in analyze directory. Halting pipeline.')
                    }

                    // 코드 체크아웃
                    checkout scm
                }
            }
        }

        // application.yml
        stage('secret.yml delete') {
            steps {
                script{
                    sh 'rm -rf /var/jenkins_home/workspace/back-analyze/back/analyze-service/src/main/resources'
                    echo "delete resources directory" 
                    // resources 폴더 새로 생성
                    sh 'mkdir -p /var/jenkins_home/workspace/back-analyze/back/analyze-service/src/main/resources'
                    echo "Recreated resources directory"

                    // 현재 상태 확인
                    sh 'ls -al /var/jenkins_home/workspace/back-analyze/back/analyze-service/src/main/resources'
                }
            }
        }

        stage('secret.yml download') {
        	steps {
            	withCredentials([file(credentialsId: 'back-analyze-application', variable: 'applicationFile')]) {
                	script {
                        echo "download application.yml"
                    	sh 'cp -f $applicationFile /var/jenkins_home/workspace/back-analyze/back/analyze-service/src/main/resources/application.yml'
                    }
        		}
            }
        }



        stage('Build Analyze-Server .JAR') {
            steps {
                script {
                    // 변경된 브랜치와 머지 대상 브랜치 출력
                    // 현재 빌드 중인 브랜치명 확인
                    def currentBranch = env.BRANCH_NAME
                    echo "Merge Target Branch : \${CHANGE_TARGET}"
                    echo "Current Branch: \${currentBranch}"

                    echo "analyze server 입니다."
                    sh 'pwd'
                    sh 'ls -al'

                    //gradlew 빌드
                    sh 'java --version'
                    sh 'chmod -R u+w+x /var/jenkins_home/workspace/back-analyze/back/analyze-service/gradlew'

                    sh '''cd /var/jenkins_home/workspace/back-analyze/back/analyze-service
                    ls -al
                    '''

                    dir('/var/jenkins_home/workspace/back-analyze/back/analyze-service') {
                        sh './gradlew clean build'
                    }
                }
            }
        }

        stage('Build Analyze-Server Image'){
            steps{
                script{
                    dockerImage = docker.build("${repository}:icon-analyze_${BUILD_NUMBER}", "--platform linux/amd64 -f back/analyze-service/Dockerfile ./back/analyze-service")
                }
            }
        }

        stage('DockerHub Login'){
            steps{
                script{
                    sh "echo \${DOCKERHUB_CREDENTIALS_PSW} | docker login -u \${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                }
            }
        }

        stage('Push Analyze-Server Image to DockerHub'){
            steps {
                script {
                    sh "docker push \${repository}:icon-analyze_\${BUILD_NUMBER}"
                }
            }
        }

        stage('Clean Analyze-Server Image'){
            steps{
                script{
                    sh "docker rmi \${repository}:icon-analyze_\${BUILD_NUMBER}"
                }
            }
        }

        stage("Garbage Collect TESTSERV") {
            steps {
                sshPublisher(
                    continueOnError: true, failOnError: false,
                    publishers: [
                        sshPublisherDesc(
                            configName: "icon-ssh",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "sudo docker kill \$(docker ps | grep icon-analyze | tr ' ' '\t' | cut -f1)"),
                                sshTransfer(execCommand: "sudo docker image prune -af"),
                                sshTransfer(execCommand: "sudo docker container prune -f"),
                                sshTransfer(execCommand: "sudo docker ps -a")
                            ]
                        )
                    ]
                )
            }
        }

        stage("Deploy"){
            steps{
                sshPublisher(
                    continueOnError: false, failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "icon-ssh",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "sudo docker rm -f icon-analyze"),
                                sshTransfer(execCommand: "sudo docker pull " + repository +":icon-analyze_${BUILD_NUMBER}"),
                                sshTransfer(execCommand: "sudo docker run -d -P --name icon-analyze --network host -e DISCOVERY_SERVER=\"${DISCOVERY_SERVER}\" " + repository + ":icon-analyze_${BUILD_NUMBER}")
                            ]
                        )
                    ]
                )
            }
        }
    }
}
